# SINTACTIC DICTS

SINTACTIC_DICT = {
    'det': 'Determiner',
    'partmod': 'Participial relation',
    'dobj': 'Direct object',
    'cc': 'Coordinating conjunction',
    'conj': 'Conjunction relation',
    'nsubj': 'Nominal subject',
    'prep': 'Prepositional relation',
    'punct': 'Punctuation',
    'pobj': 'Object of preposition',
    'amod': 'Adjectival relation',
    'poss': 'Possessive relation',
    'advmod': 'Adverbial relation',
    'aux': 'Auxiliary',
    'cop': 'Copula',
    'advcl': 'Adverbial clause relation',
    'mark': 'Marker',
    'nn': 'Noun compound relation',
    'dep': 'Dependent',
    'prt': 'Phrasal verb particle',
    'xcomp': 'open clausal complement',
    'expl': 'Expletive',
    'rcmod': 'Relative clause relation',
    'ccomp': 'Clausal complement',
    'acomp': 'Adjectival complement',
    'nsubjpass': 'Passive nominal subject',
    'auxpass': 'Passive auxiliary',
    'pcomp': 'Complement of preposition',
    'num': 'Numeric relation',
    'mwe': 'Multi-word expression',
    'quantmod': 'Quantifier relation',
    'neg': 'Negation relation',
    'appos': 'Appositional relation',
    'tmod': 'Temporal relation',
    'infmod': 'Infinitival relation',
    'number': 'Element of compound number',
    'npadvmod': 'Noun phrase as adverbial relation',
    'parataxis': 'Parataxis',
    'iobj': 'Indirect object',
    'predet': 'Predeterminer',
    'preconj': 'Preconjunct',
    'discourse': 'Discourse element',
    'csubjpass': 'Clausal passive subject',
    'csubj': 'Clausal subject',
    'possessive': 'Possessive relation',
    'root': 'Root'
}

SINTACTIC_NUM_DICT = {
    'Determiner': 0,
    'Participial relation': 1,
    'Direct object': 2,
    'Coordinating conjunction': 3,
    'Conjunction relation': 4,
    'Nominal subject': 5,
    'Prepositional relation': 6,
    'Punctuation': 7,
    'Object of preposition': 8,
    'Adjectival relation': 9,
    'Possessive relation': 10,
    'Adverbial relation': 11,
    'Auxiliary': 12,
    'Copula': 13,
    'Adverbial clause relation': 14,
    'Marker': 15,
    'Noun compound relation': 16,
    'Dependent': 17,
    'Phrasal verb particle': 18,
    'open clausal complement': 19,
    'Expletive': 20,
    'Relative clause relation': 21,
    'Clausal complement': 22,
    'Adjectival complement': 23,
    'Passive nominal subject': 24,
    'Passive auxiliary': 25,
    'Complement of preposition': 26,
    'Numeric relation': 27,
    'Multi-word expression': 28,
    'Quantifier relation': 29,
    'Negation relation': 30,
    'Appositional relation': 31,
    'Temporal relation': 32,
    'Infinitival relation': 33,
    'Element of compound number': 34,
    'Noun phrase as adverbial relation': 35,
    'Parataxis': 36,
    'Indirect object': 37,
    'Predeterminer': 38,
    'Preconjunct': 39,
    'Discourse element': 40,
    'Clausal passive subject': 41,
    'Clausal subject': 42,
    'Possessive relation': 43,
    'Root':44
}


# SEMANTIC DICTS

SEMANTIC_DICT = {
 'BV': 'Binding verb',
 'ARG1': 'First argument',
 'ARG2': 'Second argument',
 'ARG3': 'Third argument',
 'ARG4': 'Fourth argument',
 'ARG5': 'Fifth argument',
 'ARG6': 'Sixth argument',
 'ARG7': 'Seventh argument',
 'ARG8': 'Eighth argument',
 'ARG9': 'Ninth argument',
 'poss': 'Possesive relation',
 'compound': 'Compound relation',
 'subord': 'Subordination relation',
 'neg': 'Negation relation',
 'mwe': 'Multi-word expression',
 'part': 'Partitive relation',
 'conj': 'Conjunction relation',
 'loc': 'Locative relation',
 'appos': 'Appositional relation',
 'measure': 'Measure relation',
 'than': 'Comparative relation',
 'parenthetical': 'Parenthetical relation',
 'comp': 'Complement relation',
 'times': 'Multiplicative relation',
 'manner': 'Manner relation',
 'temp': 'Temporal relation',
 'of': 'Of relation',
 'root': 'Root',
}

SEMANTIC_NUM_DICT = {
    'Binding verb': 0,
    'First argument': 1,
    'Second argument': 2,
    'Third argument': 3,
    'Fourth argument': 4,
    'Fifth argument': 5,
    'Sixth argument': 6,
    'Seventh argument': 7,
    'Eighth argument': 8,
    'Ninth argument': 9,
    'Possesive relation': 10,
    'Compound relation': 11,
    'Subordination relation': 12,
    'Negation relation': 13,
    'Multi-word expression': 14,
    'Partitive relation': 15,
    'Conjunction relation': 16,
    'Locative relation': 17,
    'Appositional relation': 18,
    'Measure relation': 19,
    'Comparative relation': 20,
    'Parenthetical relation': 21,
    'Complement relation': 22,
    'Multiplicative relation': 23,
    'Manner relation': 24,
    'Temporal relation': 25,
    'Of relation': 26,
    'Root': 27,
}


# CONSTITUENCY DICTS

CONSTITUENCY_DICT = {
 'constituency relation': 'Constituency relation'
}

CONSTITUENCY_NUM_DICT = {
    'Constituency relation': 0
}

# SINTACTIC AND SEMANTIC DICTS

SIN_SEM_DICT = {
    'det': 'Determiner',
    'partmod': 'Participial relation',
    'dobj': 'Direct object',
    'cc': 'Coordinating conjunction',
    'conj': 'Conjunction relation',
    'nsubj': 'Nominal subject',
    'prep': 'Prepositional relation',
    'punct': 'Punctuation',
    'pobj': 'Object of preposition',
    'amod': 'Adjectival relation',
    'poss': 'Possessive relation',
    'advmod': 'Adverbial relation',
    'aux': 'Auxiliary',
    'cop': 'Copula',
    'advcl': 'Adverbial clause relation',
    'mark': 'Marker',
    'nn': 'Noun compound relation',
    'dep': 'Dependent',
    'prt': 'Phrasal verb particle',
    'xcomp': 'open clausal complement',
    'expl': 'Expletive',
    'rcmod': 'Relative clause relation',
    'ccomp': 'Clausal complement',
    'acomp': 'Adjectival complement',
    'nsubjpass': 'Passive nominal subject',
    'auxpass': 'Passive auxiliary',
    'pcomp': 'Complement of preposition',
    'num': 'Numeric relation',
    'mwe': 'Multi-word expression',
    'quantmod': 'Quantifier relation',
    'neg': 'Negation relation',
    'appos': 'Appositional relation',
    'tmod': 'Temporal relation',
    'infmod': 'Infinitival relation',
    'number': 'Element of compound number',
    'npadvmod': 'Noun phrase as adverbial relation',
    'parataxis': 'Parataxis',
    'iobj': 'Indirect object',
    'predet': 'Predeterminer',
    'preconj': 'Preconjunct',
    'discourse': 'Discourse element',
    'csubjpass': 'Clausal passive subject',
    'csubj': 'Clausal subject',
    'possessive': 'Possessive relation',
    'root': 'Root',
    'BV': 'Binding verb',
    'ARG1': 'First argument',
    'ARG2': 'Second argument',
    'ARG3': 'Third argument',
    'ARG4': 'Fourth argument',
    'ARG5': 'Fifth argument',
    'ARG6': 'Sixth argument',
    'ARG7': 'Seventh argument',
    'ARG8': 'Eighth argument',
    'ARG9': 'Ninth argument',
    'poss': 'Possesive relation',
    'compound': 'Compound relation',
    'subord': 'Subordination relation',
    'neg': 'Negation relation',
    'mwe': 'Multi-word expression',
    'part': 'Partitive relation',
    'conj': 'Conjunction relation',
    'loc': 'Locative relation',
    'appos': 'Appositional relation',
    'measure': 'Measure relation',
    'than': 'Comparative relation',
    'parenthetical': 'Parenthetical relation',
    'comp': 'Complement relation',
    'times': 'Multiplicative relation',
    'manner': 'Manner relation',
    'temp': 'Temporal relation',
    'of': 'Of relation',
    'root': 'Root'
}

SIN_SEM_NUM_DICT = {
    'Determiner': 0,
    'Participial relation': 1,
    'Direct object': 2,
    'Coordinating conjunction': 3,
    'Conjunction relation': 4,
    'Nominal subject': 5,
    'Prepositional relation': 6,
    'Punctuation': 7,
    'Object of preposition': 8,
    'Adjectival relation': 9,
    'Possessive relation': 43,
    'Adverbial relation': 11,
    'Auxiliary': 12,
    'Copula': 13,
    'Adverbial clause relation': 14,
    'Marker': 15,
    'Noun compound relation': 16,
    'Dependent': 17,
    'Phrasal verb particle': 18,
    'open clausal complement': 19,
    'Expletive': 20,
    'Relative clause relation': 21,
    'Clausal complement': 22,
    'Adjectival complement': 23,
    'Passive nominal subject': 24,
    'Passive auxiliary': 25,
    'Complement of preposition': 26,
    'Numeric relation': 27,
    'Multi-word expression': 28,
    'Quantifier relation': 29,
    'Negation relation': 30,
    'Appositional relation': 31,
    'Temporal relation': 65,
    'Infinitival relation': 33,
    'Element of compound number': 34,
    'Noun phrase as adverbial relation': 35,
    'Parataxis': 36,
    'Indirect object': 37,
    'Predeterminer': 38,
    'Preconjunct': 39,
    'Discourse element': 40,
    'Clausal passive subject': 41,
    'Clausal subject': 42,
    'Root': 44,
    'Binding verb': 45,
    'First argument': 46,
    'Second argument': 47,
    'Third argument': 48,
    'Fourth argument': 49,
    'Fifth argument': 50,
    'Sixth argument': 51,
    'Seventh argument': 52,
    'Eighth argument': 53,
    'Ninth argument': 54,
    'Possesive relation': 10,
    'Compound relation': 55,
    'Subordination relation': 56,
    'Partitive relation': 57,
    'Locative relation': 58,
    'Measure relation': 59,
    'Comparative relation': 60,
    'Parenthetical relation': 61,
    'Complement relation': 62,
    'Multiplicative relation': 63,
    'Manner relation': 64,
    'Of relation': 66
}


# SINTACTIC AND CONSTITUENCY DICTS

SIN_CON_DICT = {
    'det': 'Determiner',
    'partmod': 'Participial relation',
    'dobj': 'Direct object',
    'cc': 'Coordinating conjunction',
    'conj': 'Conjunction relation',
    'nsubj': 'Nominal subject',
    'prep': 'Prepositional relation',
    'punct': 'Punctuation',
    'pobj': 'Object of preposition',
    'amod': 'Adjectival relation',
    'poss': 'Possessive relation',
    'advmod': 'Adverbial relation',
    'aux': 'Auxiliary',
    'cop': 'Copula',
    'advcl': 'Adverbial clause relation',
    'mark': 'Marker',
    'nn': 'Noun compound relation',
    'dep': 'Dependent',
    'prt': 'Phrasal verb particle',
    'xcomp': 'open clausal complement',
    'expl': 'Expletive',
    'rcmod': 'Relative clause relation',
    'ccomp': 'Clausal complement',
    'acomp': 'Adjectival complement',
    'nsubjpass': 'Passive nominal subject',
    'auxpass': 'Passive auxiliary',
    'pcomp': 'Complement of preposition',
    'num': 'Numeric relation',
    'mwe': 'Multi-word expression',
    'quantmod': 'Quantifier relation',
    'neg': 'Negation relation',
    'appos': 'Appositional relation',
    'tmod': 'Temporal relation',
    'infmod': 'Infinitival relation',
    'number': 'Element of compound number',
    'npadvmod': 'Noun phrase as adverbial relation',
    'parataxis': 'Parataxis',
    'iobj': 'Indirect object',
    'predet': 'Predeterminer',
    'preconj': 'Preconjunct',
    'discourse': 'Discourse element',
    'csubjpass': 'Clausal passive subject',
    'csubj': 'Clausal subject',
    'possessive': 'Possessive relation',
    'root': 'Root',
    'constituency relation': 'Constituency relation'
}

SIN_CON_NUM_DICT = {
    'Determiner': 0,
    'Participial relation': 1,
    'Direct object': 2,
    'Coordinating conjunction': 3,
    'Conjunction relation': 4,
    'Nominal subject': 5,
    'Prepositional relation': 6,
    'Punctuation': 7,
    'Object of preposition': 8,
    'Adjectival relation': 9,
    'Possessive relation': 10,
    'Adverbial relation': 11,
    'Auxiliary': 12,
    'Copula': 13,
    'Adverbial clause relation': 14,
    'Marker': 15,
    'Noun compound relation': 16,
    'Dependent': 17,
    'Phrasal verb particle': 18,
    'open clausal complement': 19,
    'Expletive': 20,
    'Relative clause relation': 21,
    'Clausal complement': 22,
    'Adjectival complement': 23,
    'Passive nominal subject': 24,
    'Passive auxiliary': 25,
    'Complement of preposition': 26,
    'Numeric relation': 27,
    'Multi-word expression': 28,
    'Quantifier relation': 29,
    'Negation relation': 30,
    'Appositional relation': 31,
    'Temporal relation': 32,
    'Infinitival relation': 33,
    'Element of compound number': 34,
    'Noun phrase as adverbial relation': 35,
    'Parataxis': 36,
    'Indirect object': 37,
    'Predeterminer': 38,
    'Preconjunct': 39,
    'Discourse element': 40,
    'Clausal passive subject': 41,
    'Clausal subject': 42,
    'Possessive relation': 43,
    'Root':44,
    'Constituency relation': 45
}


# SEMANTIC AND CONSTITUENCY DICTS

SEM_CON_DICT = {
    'BV': 'Binding verb',
    'ARG1': 'First argument',
    'ARG2': 'Second argument',
    'ARG3': 'Third argument',
    'ARG4': 'Fourth argument',
    'ARG5': 'Fifth argument',
    'ARG6': 'Sixth argument',
    'ARG7': 'Seventh argument',
    'ARG8': 'Eighth argument',
    'ARG9': 'Ninth argument',
    'poss': 'Possesive relation',
    'compound': 'Compound relation',
    'subord': 'Subordination relation',
    'neg': 'Negation relation',
    'mwe': 'Multi-word expression',
    'part': 'Partitive relation',
    'conj': 'Conjunction relation',
    'loc': 'Locative relation',
    'appos': 'Appositional relation',
    'measure': 'Measure relation',
    'than': 'Comparative relation',
    'parenthetical': 'Parenthetical relation',
    'comp': 'Complement relation',
    'times': 'Multiplicative relation',
    'manner': 'Manner relation',
    'temp': 'Temporal relation',
    'of': 'Of relation',
    'root': 'Root',
    'constituency relation': 'Constituency relation'
}

SEM_CON_NUM_DICT = {
    'Binding verb': 0,
    'First argument': 1,
    'Second argument': 2,
    'Third argument': 3,
    'Fourth argument': 4,
    'Fifth argument': 5,
    'Sixth argument': 6,
    'Seventh argument': 7,
    'Eighth argument': 8,
    'Ninth argument': 9,
    'Possesive relation': 10,
    'Compound relation': 11,
    'Subordination relation': 12,
    'Negation relation': 13,
    'Multi-word expression': 14,
    'Partitive relation': 15,
    'Conjunction relation': 16,
    'Locative relation': 17,
    'Appositional relation': 18,
    'Measure relation': 19,
    'Comparative relation': 20,
    'Parenthetical relation': 21,
    'Complement relation': 22,
    'Multiplicative relation': 23,
    'Manner relation': 24,
    'Temporal relation': 25,
    'Of relation': 26,
    'Root': 27,
    'Constituency relation': 28
}


# SINTACTIC, SEMANTIC AND CONSTITUENCY DICTS

SIN_SEM_CON_DICT = {
    'det': 'Determiner',
 'partmod': 'Participial relation',
 'dobj': 'Direct object',
 'cc': 'Coordinating conjunction',
 'conj': 'Conjunction relation',
 'nsubj': 'Nominal subject',
 'prep': 'Prepositional relation',
 'punct': 'Punctuation',
 'pobj': 'Object of preposition',
 'amod': 'Adjectival relation',
 'poss': 'Possesive relation',
 'advmod': 'Adverbial relation',
 'aux': 'Auxiliary',
 'cop': 'Copula',
 'advcl': 'Adverbial clause relation',
 'mark': 'Marker',
 'nn': 'Noun compound relation',
 'dep': 'Dependent',
 'prt': 'Phrasal verb particle',
 'xcomp': 'open clausal complement',
 'expl': 'Expletive',
 'rcmod': 'Relative clause relation',
 'ccomp': 'Clausal complement',
 'acomp': 'Adjectival complement',
 'nsubjpass': 'Passive nominal subject',
 'auxpass': 'Passive auxiliary',
 'pcomp': 'Complement of preposition',
 'num': 'Numeric relation',
 'mwe': 'Multi-word expression',
 'quantmod': 'Quantifier relation',
 'neg': 'Negation relation',
 'appos': 'Appositional relation',
 'tmod': 'Temporal relation',
 'infmod': 'Infinitival relation',
 'number': 'Element of compound number',
 'npadvmod': 'Noun phrase as adverbial relation',
 'parataxis': 'Parataxis',
 'iobj': 'Indirect object',
 'predet': 'Predeterminer',
 'preconj': 'Preconjunct',
 'discourse': 'Discourse element',
 'csubjpass': 'Clausal passive subject',
 'csubj': 'Clausal subject',
 'possessive': 'Possessive relation',
 'root': 'Root',
 'BV': 'Binding verb',
 'ARG1': 'First argument',
 'ARG2': 'Second argument',
 'ARG3': 'Third argument',
 'ARG4': 'Fourth argument',
 'ARG5': 'Fifth argument',
 'ARG6': 'Sixth argument',
 'ARG7': 'Seventh argument',
 'ARG8': 'Eighth argument',
 'ARG9': 'Ninth argument',
 'compound': 'Compound relation',
 'subord': 'Subordination relation',
 'part': 'Partitive relation',
 'loc': 'Locative relation',
 'measure': 'Measure relation',
 'than': 'Comparative relation',
 'parenthetical': 'Parenthetical relation',
 'comp': 'Complement relation',
 'times': 'Multiplicative relation',
 'manner': 'Manner relation',
 'temp': 'Temporal relation',
 'of': 'Of relation',
 'constituency relation': 'Constituency relation'
}


SIN_SEM_CON_NUM_DICT = {
    'Determiner': 0,
    'Participial relation': 1,
    'Direct object': 2,
    'Coordinating conjunction': 3,
    'Conjunction relation': 4,
    'Nominal subject': 5,
    'Prepositional relation': 6,
    'Punctuation': 7,
    'Object of preposition': 8,
    'Adjectival relation': 9,
    'Possessive relation': 43,
    'Adverbial relation': 11,
    'Auxiliary': 12,
    'Copula': 13,
    'Adverbial clause relation': 14,
    'Marker': 15,
    'Noun compound relation': 16,
    'Dependent': 17,
    'Phrasal verb particle': 18,
    'open clausal complement': 19,
    'Expletive': 20,
    'Relative clause relation': 21,
    'Clausal complement': 22,
    'Adjectival complement': 23,
    'Passive nominal subject': 24,
    'Passive auxiliary': 25,
    'Complement of preposition': 26,
    'Numeric relation': 27,
    'Multi-word expression': 28,
    'Quantifier relation': 29,
    'Negation relation': 30,
    'Appositional relation': 31,
    'Temporal relation': 65,
    'Infinitival relation': 33,
    'Element of compound number': 34,
    'Noun phrase as adverbial relation': 35,
    'Parataxis': 36,
    'Indirect object': 37,
    'Predeterminer': 38,
    'Preconjunct': 39,
    'Discourse element': 40,
    'Clausal passive subject': 41,
    'Clausal subject': 42,
    'Root': 44,
    'Binding verb': 45,
    'First argument': 46,
    'Second argument': 47,
    'Third argument': 48,
    'Fourth argument': 49,
    'Fifth argument': 50,
    'Sixth argument': 51,
    'Seventh argument': 52,
    'Eighth argument': 53,
    'Ninth argument': 54,
    'Possesive relation': 10,
    'Compound relation': 55,
    'Subordination relation': 56,
    'Partitive relation': 57,
    'Locative relation': 58,
    'Measure relation': 59,
    'Comparative relation': 60,
    'Parenthetical relation': 61,
    'Complement relation': 62,
    'Multiplicative relation': 63,
    'Manner relation': 64,
    'Of relation': 66,
    'constituency relation': 67
 }