"\"\"\"Utilities to visualise analytics generated by the pipeline.\"\"\""

from .structural_heatmaps import (
    compute_structural_difference_matrix,
    generate_structural_correlation_heatmaps,
    generate_structural_difference_heatmaps,
    plot_clustered_correlation_heatmap,
    plot_structural_correlation_heatmap,
    plot_structural_difference_heatmap,
)
from .semantic_rank import (
    generate_token_rank_differences,
    generate_token_rank_histograms,
    plot_token_rank_difference,
    plot_token_rank_histogram,
)
from .semantic_score import (
    generate_token_score_densities,
    generate_token_score_differences,
    generate_token_score_ranking,
    plot_token_score_density,
    plot_token_score_difference,
    generate_token_position_differences,
    plot_token_position_difference,
)
from .semantic_token_frequency import (
    generate_token_frequency_charts,
)
from .semantic_sparsity import generate_sparsity_visuals
from .semantic_confidence import generate_confidence_threshold_visuals
from .semantic_embeddings import (
    generate_embedding_importance_correlation,
    generate_embedding_neighborhoods,
)

__all__ = [
    "plot_structural_correlation_heatmap",
    "generate_structural_correlation_heatmaps",
    "compute_structural_difference_matrix",
    "plot_structural_difference_heatmap",
    "generate_structural_difference_heatmaps",
    "plot_clustered_correlation_heatmap",
    "plot_token_rank_difference",
    "generate_token_rank_differences",
    "plot_token_score_density",
    "generate_token_score_densities",
    "plot_token_score_difference",
    "generate_token_score_differences",
    "plot_token_position_difference",
    "generate_token_position_differences",
    "plot_token_rank_histogram",
    "generate_token_rank_histograms",
    "generate_token_frequency_charts",
    "generate_token_score_ranking",
    "generate_sparsity_visuals",
    "generate_confidence_threshold_visuals",
    "generate_embedding_importance_correlation",
    "generate_embedding_neighborhoods",
]
